Migrate CSD02 changes from secvisogram repo
secvisogram/csaf-validator-lib pull request #1
Opened 2022-03-18 14:37 UTC by domachine

This PR applies the changes from https://github.com/secvisogram/secvisogram/pull/234 .

2022-03-18 20:23 UTC, tschmidtb51 requested changes
The one issue in [tests/all/schemaTests.js](https://github.com/secvisogram/csaf-validator-lib/pull/1/files/fece406b602fb82d13b8fd9aca0762943b7119a3#diff-c20eab42e9d631122d38b737b132e3f9c085450c96b5058709a2598d693556d7) seems to be blocking, all other are just minors / informational...

2022-03-18 20:23 UTC, tschmidtb51 commented on lib/schemaTests/csaf_2_0/schema.js
> +              "Contains the canonical descriptor or 'friendly name' of the branch.",
Just out of curiosity: In other lines you used `'` to mark the string. Should the `'` inside be escaped instead?

2022-03-22 12:20 UTC, domachine commented on tests/all.js
> +        if ('expectedNumberOfErrors' in documentTest) {
The reason here is the type inference. Since I changed this to `@type {const}` in the test files, these are now strictly inferred. So this correctly hints the typescript compiler here.

2022-03-22 12:22 UTC, domachine commented on lib/schemaTests/csaf_2_0_strict/schema.js
> +          pattern: '^[^\\s\\-_\\.](.*[^\\s\\-_\\.])?$',
This is okay. I converted this since Node.js doesn't allow `.json` imports with ecma modules anymore. This conversion was done automatically using prettier. The patterns are still correct.

2022-03-22 12:24 UTC, domachine commented on tests/all.js
> +          : `Mandatory Test #${i + 1}`
No optional and informative tests are run in separate `describe` blocks.

2022-03-22 12:29 UTC, domachine commented on lib/schemaTests/csaf_2_0/schema.js
> +              "Contains the canonical descriptor or 'friendly name' of the branch.",
This is a convention of prettier since the string uses single quotes which would have to be escaped using backslash otherwise.

2022-03-22 12:38 UTC, tschmidtb51 commented on tests/all/schemaTests.js
> +import minimalGenericCSAFDoc from '../shared/minimalCSAFBaseDoc.js'
Done in [b495399](https://github.com/secvisogram/csaf-validator-lib/pull/1/commits/b495399347155ae1a75e2138a2a6eb88e62826f0).

2022-03-22 12:38 UTC, tschmidtb51 approved these changes
LGTM

2022-03-23 09:10 UTC, cloeser approved these changes
Not directly related to this MR, but we could use constants for the categories ("csaf_security_advisory"). Makes future changes easier and prevents typos.

LGTM

2022-03-23 09:12 UTC, merged