Misc test issues
secvisogram/csaf-validator-lib pull request #12
Opened 2022-04-20 09:07 UTC by domachine

This PR fixes some issues found in newly created optional and informative tests

2022-04-20 12:30 UTC, valentindey commented on lib/informativeTests/informativeTest_6_3_7.js
> +    if (!res.statusCode || 400 < res.statusCode) {
Why do we add the check `!res.statusCode` here? This additional check is not performed in `testURL` of test 6.3.6

2022-04-20 12:58 UTC, domachine commented on lib/informativeTests/informativeTest_6_3_7.js
> +    if (!res.statusCode || 400 < res.statusCode) {
This is the case when `res.statusCode` is `0` in case of a network error which is included in `< 200` of `6.3.6`

2022-04-20 13:36 UTC, valentindey requested changes

2022-04-20 13:36 UTC, valentindey commented on lib/informativeTests/informativeTest_6_3_7.js
>          instancePath: `/document/references/${i}/url`,
The specification requires test 6.3.7 to also check the urls at `/vulnerabilities[]/references[]/url`

2022-04-20 16:25 UTC, tschmidtb51 reviewed
See comment.

2022-04-27 08:27 UTC, valentindey submitted a review, later dismissed

2022-04-27 10:16 UTC, tschmidtb51 requested changes
Please have a look at my comments. We can discuss questions in the meeting...

2022-04-27 10:16 UTC, tschmidtb51 commented on tests/all/informativeTests.js
> +        m.get('https://example.invalid')
Please see my comment above and test both variants...

2022-04-27 10:16 UTC, tschmidtb51 commented on tests/all/informativeTests.js
> +    title: 'Informative test 6.3.7 accepts 302 redirect',
What is the difference to test in line 436?

2022-04-27 10:16 UTC, tschmidtb51 commented on tests/all/optionalTests.js
> +  ...[
Should add the test case with the informational advisory profile.

2022-04-27 10:16 UTC, tschmidtb51 commented on tests/all/optionalTests.js
> +              last_affected: ['CSAFPID-9080700'],
Looking at that it matches because of the `product_status` not the score.

2022-04-27 10:17 UTC, tschmidtb51 commented
> @valentindey @tschmidtb51 I think I addressed all your issues. Could you recheck, and approve if appropriate?

Sorry about the delay. Just added the review.

2022-04-27 12:48 UTC, domachine commented
> > @valentindey @tschmidtb51 I think I addressed all your issues. Could you recheck, and approve if appropriate?
> 
> Sorry about the delay. Just added the review.

Thank you very much for review. I think I could fix all issues.

2022-04-27 18:22 UTC, tschmidtb51 approved these changes
LGTM.

2022-04-28 12:44 UTC, merged