fix: keys sorted alphabetically 6_2_13
secvisogram/csaf-validator-lib pull request #157
Opened 2024-02-21 09:56 UTC by MarcoKorinth

Fixes #150 

# Changes
Adding a return statement for arrays

The function executes recursive calls for all items in an array.
An array itself cannot be tested though, because it has no keys that could be alphabetically sorted.
This fix makes sure that the function returns after the items of the array have all been checked.

```javascript
  const checkObjectKeysSorting = (collator, prefix, obj) => {
    if (typeof obj !== 'object' || obj == null) return
    if (Array.isArray(obj)) {
      obj.forEach((e, i) => {
        checkObjectKeysSorting(collator, prefix + '/' + i, e)
      })
      return // <-- this was added
    }

  ...
}
```

2024-02-21 16:15 UTC, tschmidtb51 requested changes
I haven't tested it yet deeply, but I have a hunch that this fails the intend. Therefore, please add a test that tests that incorrect orders in items of arrays are still detected, e.g.:

```
{
      "summary" : "Debian Security Advisory DSA-5588 vom 2023-12-24",
      "url" : "https://www.debian.org/security/2023/dsa-5588",
      "category" : "external"
    }, 
```

However, the following one should not be reported upon:
```
"known_affected" : [ "T031788", "T029035",  "T031931", "T031787"]

2024-02-22 02:55 UTC, MarcoKorinth commented
For clarification: Incorrect orders of array items isn't detected anymore, which covers your second example.

But there is no change in objects, like in your first example.
Note the different bracket enclosures `{}` and `[]`.

I think testing the sorting of object keys is covered by the 6.2.13 test as it is right now.
But if you want to I can add your example as a second test.

Current test:

```javascript
{
  title: 'Optional test 6.2.13 detects invalid sorting',
  content: (() => {
    const doc = {
      ...minimalDoc,
      document: {
        ...minimalDoc.document,
        csaf_version: '2.0',
        category: 'generic_csaf',
      },
    }

    // Is needed to wipe the position of entries
    delete (/** @type {any} */ (doc.document).csaf_version)
    delete (/** @type {any} */ (doc.document).category)
    doc.document.csaf_version = '2.0'
    doc.document.category = 'generic_csaf'

    return doc
  })(),
  expectedNumberOfWarnings: 1,
},
```

2024-02-26 21:46 UTC, tschmidtb51 commented
You are right, those tests should be provided upstream. I'll mark that as draft until the test are provided by upstream.

2024-02-27 12:09 UTC, MarcoKorinth commented
TODO: add comment for return

2024-02-27 12:41 UTC, tschmidtb51 approved these changes
LGTM

2024-02-27 14:46 UTC, merged