Export CWE catalogue
secvisogram/csaf-validator-lib pull request #22
Opened 2022-05-18 13:49 UTC by domachine

This PR updates and exposes the cwe catalogue from https://cwe.mitre.org/data/downloads.html.

**HEADS UP**: This PR bases on #9 and seems to be larger than it actually is.

2022-05-23 07:45 UTC, valentindey commented on tests/cwe.js
> +    expect(cwe.weaknesses).to.deep.equal(cweCatalogue.weaknesses)
this test feels somewhat redundant as both, `cwe` and `cweCatalogue` are imported from the same file :thinking:

2022-05-23 07:47 UTC, valentindey commented
I only checked the changes added on top of #9 , these LGTM.

2022-05-23 07:47 UTC, valentindey approved these changes

2022-06-07 13:33 UTC, domachine commented on tests/cwe.js
> +    expect(cwe.weaknesses).to.deep.equal(cweCatalogue.weaknesses)
Yes, but I wanted to express that the interface is exported and simulate importing like a consumer of the lib would do.

2022-06-07 14:11 UTC, valentindey commented on tests/cwe.js
> +    expect(cwe.weaknesses).to.deep.equal(cweCatalogue.weaknesses)
I'd still argue about the significance of this test but am also fine with leaving it there.

2022-06-07 14:12 UTC, valentindey approved these changes

2022-06-07 14:15 UTC, domachine commented on tests/cwe.js
> +    expect(cwe.weaknesses).to.deep.equal(cweCatalogue.weaknesses)
So, let's argue 😛 ... just kiddin'. If you want, I can remove it, but I feel better to have it there, especially when extending this and having a spot to continue.

2022-06-20 23:23 UTC, tschmidtb51 submitted a review, later dismissed
Just a minor comment to add a link :-) Other than that: LGTM.

2022-06-20 23:23 UTC, tschmidtb51 commented on scripts/cwe-importCatalogue.js
> +const [, , REGISTRY_FILE] = process.argv
Maybe add a link here or in the Readme where to download the [latest CWE catalogue](https://cwe.mitre.org/data/xml/cwec_latest.xml.zip)...

2022-07-15 14:14 UTC, tschmidtb51 requested changes
Please regenerate the cwec.js again - there is already a new version (4.8) available :see_no_evil:

2022-07-15 14:26 UTC, domachine commented
> Please regenerate the cwec.js again - there is already a new version (4.8) available 🙈

The script definitely pays off 😅

2022-07-15 14:27 UTC, merged