CSD02 mandatory tests
secvisogram/csaf-validator-lib pull request #3
Opened 2022-03-30 14:05 UTC by domachine

This PR includes the additional mandatory tests from CSD02.

2022-03-31 18:56 UTC, tschmidtb51 commented
@domachine Do you have a small script that imports the library and validates a file against one test? That would help me to test some edge cases of the implementation.

Just from looking at the code I couldn't spot anything obvious...

2022-04-01 07:55 UTC, domachine commented
> @domachine Do you have a small script that imports the library and validates a file against one test? That would help me to test some edge cases of the implementation.
> 
> Just from looking at the code I couldn't spot anything obvious...

Yes, I can throw one together. But if you want, you could add these edge cases to the `documentTests.js` file to include them in the test-suite. Just copy and paste the JSON into the `content` field. Since JSON is also valid JS, no changes are needed.

2022-04-01 07:58 UTC, tschmidtb51 commented
> Yes, I can throw one together.

I wouldn't mind if you could do that. I would like to use that in the TC's repo to make sure the example files fail the right tests...

2022-04-01 09:00 UTC, domachine commented
> > Yes, I can throw one together.
> 
> I wouldn't mind if you could do that. I would like to use that in the TC's repo to make sure the example files fail the right tests...

Here is a git-patch. Save it on your disk and run `git apply <patch-file-path>` from within the `csaf-validator-lib` repo. Then you can run the script using the following command: `./scripts/runTest.js <doc-file> mandatoryTest_6_1_1`. `mandatoryTest_6_1_1` is a sample here. You can insert any test name from `lib/mandatoryTests.js`, `lib/optionalTests.js`, `lib/schemaTests.js` and `lib/schemaTests.js`.

[run_test_script.patch](https://github.com/secvisogram/csaf-validator-lib/files/8396272/run_test_script.txt)

2022-04-06 09:26 UTC, valentindey commented on lib/mandatoryTests/mandatoryTest_6_1_33.js
> +            !flagReported &&
Why do we need this additional check here? Is `flagReported` even needed? If I see it correctly, it will always be the same value as `productIDsWithVexJustificationCode.has(productID)` or am I missing something?

2022-04-06 09:26 UTC, valentindey commented on lib/mandatoryTests/mandatoryTest_6_1_21.js
> +        message: `does not start with a version of 0 or 1`,
Could we be a little more clear in the message what the error is? Without the context of sorting by date, one might not know what "starting" means.

Side note:
I found it to be somewhat obfuscated that in case of semantic versioning the major version is selected by how `parseInt` works.

2022-04-06 09:33 UTC, domachine commented on lib/mandatoryTests/mandatoryTest_6_1_33.js
> +            !flagReported &&
Not exactly. It's a little bit confusing here, since the reporting is based on the flag and not on the product-id. You could refer to the product-id using `product_ids` and `group_ids` which would result in a double report of the flag. I have a test for that. Remove this line and you will see one of them fail.

2022-04-06 09:34 UTC, domachine commented on lib/mandatoryTests/mandatoryTest_6_1_30.js
> +          message: 'integer and semantic versioning',
I took the wording of the test in the spec here but I think you're right. What do you think @tschmidtb51 ?

2022-04-06 09:35 UTC, domachine commented on lib/mandatoryTests/mandatoryTest_6_1_31.js
> +            path: `${path}/${branchIndex}`,
Good catch! Thank you very much.

2022-04-06 09:38 UTC, domachine commented on lib/mandatoryTests/mandatoryTest_6_1_21.js
> +        message: `does not start with a version of 0 or 1`,
For the message part: I'm pretty sure there is a better wording 😅 

For the part with `parseInt`: The thing is that using this technique, I do not need to check explicitly if there is semver or numeric versioning in place. But I'm definitely open for improvements, any suggestions?

2022-04-06 10:08 UTC, valentindey commented on lib/mandatoryTests/mandatoryTest_6_1_21.js
> +        message: `does not start with a version of 0 or 1`,
Maybe sth. like `'revision history does not start with a version of 0 or 1 when sorted by date'` makes it more clear.

I just stumbled over the `parseInt` part initially thinking it doesn't even take care of semver. Checking in detail, I totally get it and see how it is easier. However, a short comment might help future readers of the code to understand more quickly.

2022-04-06 10:09 UTC, tschmidtb51 commented on lib/mandatoryTests/mandatoryTest_6_1_30.js
> +                  number: { type: 'string' },
Why is `number` an optional property? According to the schema it should be mandatory...

2022-04-06 10:15 UTC, tschmidtb51 commented on lib/mandatoryTests/mandatoryTest_6_1_30.js
> +                  number: { type: 'string' },
Ah, okay. Now I understand that.

2022-04-06 11:41 UTC, tschmidtb51 requested changes
Please see my comments.

2022-04-06 11:41 UTC, tschmidtb51 commented on lib/mandatoryTests/mandatoryTest_6_1_21.js
> +        message: `does not start with a version of 0 or 1`,
Regards message: Maybe, we could write `does not start with major version of 0 or 1`.

2022-04-06 11:41 UTC, tschmidtb51 commented on lib/mandatoryTests/mandatoryTest_6_1_33.js
> +            !flagReported &&
I had a look into it:
It is actually checking twice: If you just remove line 87 - nothing happens as line 65 would catch that.

Line 65 is definitely needed to prevent double reporting...

2022-04-06 13:31 UTC, domachine commented
Alright I addressed the issues and rebased the history.

2022-04-06 13:50 UTC, valentindey commented on lib/mandatoryTests/mandatoryTest_6_1_21.js
> +        message: `does not start with a version of 0 or 1`,
As for the error message, I am fine, so I'm resolving this discussion. @tschmidtb51 please re-open if you miss the `major` keyword.

The comment on `parseInt` makes it more clear :+1:

2022-04-06 13:51 UTC, valentindey commented on lib/mandatoryTests/mandatoryTest_6_1_33.js
> +            !flagReported &&
Now that lines 77-80 and 87-90 are actually the same, it could be simplified further, moving the handling of a `porductID` into the `error` function. But I'm not insisting on that and would be fine with resolving the discussion.

2022-04-06 13:52 UTC, valentindey approved these changes

2022-04-06 13:57 UTC, tschmidtb51 commented on tests/all/documentTests.js
> +    title: 'Mandatory Test 6.1.33 skips multiple flags across vulnerabilities',
`Skip` seems to be misleading in that context.
```suggestion
    title: 'Mandatory Test 6.1.33 does not evaluate multiple flags across vulnerabilities',

2022-04-06 13:58 UTC, tschmidtb51 reviewed
Just a minor wording change suggested...

2022-04-06 14:01 UTC, domachine commented
> Just a minor wording change suggested...

Fixed 🙂

2022-04-06 14:18 UTC, tschmidtb51 approved these changes
LGTM

2022-04-06 14:20 UTC, merged