feat: add strict mode option
secvisogram/csaf-validator-lib pull request #51
Opened 2022-08-24 15:00 UTC by domachine

Closes #46

2022-08-24 19:28 UTC, tschmidtb51 requested changes
Please state more clearly that passing an function that is not defined in the lib may result in an (unintended) code execution. The calling function is in such case responsible of checking whether that execution is wanted or not.

2022-08-24 19:31 UTC, tschmidtb51 commented on lib/validate.js
> +export default async function (tests, doc, { strict = true } = {}) {
Why do we do that as an object? For extensibility? => Great.

However, I would need a closer look at `{ strict = true } = {}`. That looks interesting as it seems to be a double assignment that I can't figure out right now. I should probably look at that with fresh eyes.

2022-08-25 08:19 UTC, domachine commented on lib/validate.js
> +export default async function (tests, doc, { strict = true } = {}) {
This double equal sign is due to the feature that the strict option is optional as well as the complete options object.

2022-08-25 08:20 UTC, domachine commented
> Please state more clearly that passing an function that is not defined in the lib may result in an (unintended) code execution. The calling function is in such case responsible of checking whether that execution is wanted or not.

Do you have a suggestion for a good description?

2022-08-29 08:57 UTC, tschmidtb51 commented on lib/validate.js
> +export default async function (tests, doc, { strict = true } = {}) {
Thanks

2022-08-29 09:06 UTC, tschmidtb51 commented
> > Please state more clearly that passing an function that is not defined in the lib may result in an (unintended) code execution. The calling function is in such case responsible of checking whether that execution is wanted or not.
> 
> Do you have a suggestion for a good description?

I didn't when I wrote the first review - so I just told the concept what I think we need.

2022-08-29 09:23 UTC, tschmidtb51 requested changes
I would suggest to add a section "Strict Mode" in the the README. Here is a rough draft. Feel free to adopt.

```
## Strict Mode

In the default setting, the library checks whether the test that should be executed was defined in the library. Otherwise, it throws an error.
To extend the library, that check can be turned of. **In such case, the calling function is responsible of checking whether the test function passed to the `csaf-validator-lib` is benign. Calling arbitrary functions (especially those resulting from user input) may result in a code execution vulnerability. Therefore, the check of the test function to determine whether it is benign MUST be done before calling it.**
To proceed this dangerous path, set `strict = false`.

2022-08-29 09:23 UTC, tschmidtb51 commented on lib/validate.js
> +      throw new Error('Insecure test function detected')
```suggestion
      throw new Error('Execution of test functions not defined in the library is prohibited. See https://github.com/secvisogram/csaf-validator-lib#strict-mode for more details.')

2022-08-29 09:23 UTC, tschmidtb51 commented on tests/validate.js
> +      expect(e.message).to.equal('Insecure test function detected')
See above

2022-08-29 09:23 UTC, tschmidtb51 commented on README.md
> +This function validates the given document against the given tests. The `strict` option (default `true`) throws if an unknown test function was passed.
Maybe also link here to the section strict mode:
```suggestion
This function validates the given document against the given tests. The `strict` option (default `true`) throws an error if an unknown test function was passed. See [Strict Mode](#strict-mode) for details.

2022-08-29 09:23 UTC, tschmidtb51 commented on README.md
> +This function strips empty nodes and nodes with errors. The `strict` option (default `true`) throws if an unknown test function was passed.
Same applies here.

2022-08-29 14:02 UTC, valentindey submitted a review, later dismissed

2022-08-29 14:02 UTC, valentindey commented on tests/validate.js
> +      expect(e.message).to.equal('Insecure test function detected')
```suggestion
      expect(e.message).to.contain('Execution of test functions not defined in the library is prohibited.')
```

2022-08-29 14:06 UTC, valentindey commented
> I would suggest to add a section "Strict Mode" in the the README. Here is a rough draft. Feel free to adopt.
> 
> ```
> ## Strict Mode
> 
> In the default setting, the library checks whether the test that should be executed was defined in the library. Otherwise, it throws an error.
> To extend the library, that check can be turned of. **In such case, the calling function is responsible of checking whether the test function passed to the `csaf-validator-lib` is benign. Calling arbitrary functions (especially those resulting from user input) may result in a code execution vulnerability. Therefore, the check of the test function to determine whether it is benign MUST be done before calling it.**
> To proceed this dangerous path, set `strict = false`.
> ```

To me that description would be clear. Just make sure to correct the typo "turned _off_* when adding such a section @domachine :slightly_smiling_face:

2022-08-31 19:26 UTC, tschmidtb51 reviewed
Only some minor wording and format things - other than that okay for me.

2022-08-31 19:26 UTC, tschmidtb51 commented on README.md
> +## Strict Mode
Maybe, use one level more... (it still kinda belongs to "How to use")
```suggestion
### Strict Mode

2022-08-31 19:26 UTC, tschmidtb51 commented on README.md
> +To extend the library, that check can be turned off. **In such case, the calling function is responsible of checking whether the test function passed to the `csaf-validator-lib` is benign. Calling ar
I try to limit the bold to the important parts.
```suggestion
To extend the library, that check can be turned off. In such case, **the calling function is responsible for checking** whether the test function passed to the `csaf-validator-lib` is benign. **Calling arbitrary** functions (especially those resulting from user input) may result in a **code execution vulnerability**. Therefore, the check of the test function to determine whether it is benign **MUST be done before calling** it.

2022-08-31 19:26 UTC, tschmidtb51 commented on package-lock.json
> +  "version": "0.1.0"
Are both of them updated automatically?

2022-08-31 19:26 UTC, tschmidtb51 commented on README.md
> +This function validates the given document against the given tests. The `strict` option (default `true`) throws an error if an unknown test function was passed. See [Strict Mode](#strict-mode) for de
```suggestion
This function validates the given document against the given tests. The `strict` option (default `true`) throws an error if an unknown test function was passed. See [Strict Mode](#strict-mode) for more details.

2022-09-01 09:55 UTC, domachine commented on package-lock.json
> +  "version": "0.1.0"
Yes this was done using `npm version minor`

2022-09-01 10:17 UTC, tschmidtb51 commented on package-lock.json
> +  "version": "0.1.0"
Perfect.

2022-09-01 12:00 UTC, tschmidtb51 approved these changes
LGTM

2022-09-01 13:22 UTC, merged