fix: fix too early loop exit
secvisogram/csaf-validator-lib pull request #71
Opened 2022-10-21 11:33 UTC by domachine

Fix #56

2022-10-24 13:20 UTC, tschmidtb51 requested changes
I had a look into it and found a few things. Please have a look at my comments.

This should result in the following information count:
- `oasis_csaf_tc-csaf_2_0-2021-6-3-09-01.json`: 1
- `oasis_csaf_tc-csaf_2_0-2021-6-3-09-02.json`: 2
- `oasis_csaf_tc-csaf_2_0-2021-6-3-09-03.json`: 4
- `oasis_csaf_tc-csaf_2_0-2021-6-3-09-04.json`: 2
- `oasis_csaf_tc-csaf_2_0-2021-6-3-09-05.json`: 2
- `oasis_csaf_tc-csaf_2_0-2021-6-3-09-06.json`: 6

2022-10-24 13:20 UTC, tschmidtb51 commented on lib/informativeTests/informativeTest_6_3_9.js
> +              break
This leads to the point, where only the first missing category is reported. I guess, we should report them all at once.
```suggestion
```

2022-10-24 13:20 UTC, tschmidtb51 commented on lib/informativeTests/informativeTest_6_3_9.js
> +              break
:+1:

2022-10-24 13:20 UTC, tschmidtb51 commented on lib/informativeTests/informativeTest_6_3_9.js
>            const sortedIndexes = mandatoryCategoryIndexes
Consequently, we need to filter those values, that are not present. The following code could work - but needs a bit polishing in terns of naming variables (esp. `presentIndexes`):
```
//remove missing categories
          const presentIndexes = mandatoryCategoryIndexes
            .filter((i) => i.index > -1)
          const sortedIndexes = presentIndexes
            .slice()
            .sort((a, z) => a.index - z.index)
          for (const [i, sortedIndex] of sortedIndexes.entries()) {
            if (sortedIndex.category !== presentIndexes[i].category) {

2022-10-26 08:25 UTC, tschmidtb51 reviewed
Implementation looks good. Please add https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-06.json to complete.

2022-10-26 08:40 UTC, domachine commented
> Implementation looks good. Please add https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/test/validator/data/informative/oasis_csaf_tc-csaf_2_0-2021-6-3-09-06.json to complete.

Yes, missed that! Thank you.

2022-10-26 08:41 UTC, tschmidtb51 submitted a review, later dismissed
LGTM

2022-10-26 08:59 UTC, valentindey approved these changes

2022-10-26 08:59 UTC, valentindey commented on tests/informativeTest_6_3_9.js
> +        ])
couldn't this be moved out of the loop?

2022-10-26 10:16 UTC, tschmidtb51 commented on tests/informativeTest_6_3_9.js
> +        ])
Good catch. I guess it could/should....

2022-10-26 11:43 UTC, domachine commented on tests/informativeTest_6_3_9.js
> +        ])
Alright, I changed that and therefore need reviews again ;-)

2022-10-26 11:44 UTC, valentindey approved these changes

2022-10-26 12:04 UTC, tschmidtb51 approved these changes
LGTM

2022-10-26 14:07 UTC, merged