CSD02 Additional Tests
secvisogram/csaf-validator-lib pull request #9
Opened 2022-04-08 09:53 UTC by domachine

This PR includes the missing optional and informative tests for CSD02.

2022-04-27 07:53 UTC, domachine commented
See my issue #15 for the missing test 6.2.20.

2022-05-23 13:37 UTC, valentindey commented on scripts/bcp-importSubtags.js
> +  const subtags = []
It's a little confusing to reuse `subtags` here when it's used in the outer scope already.

2022-05-23 13:37 UTC, valentindey commented on scripts/bcp-importSubtags.js
> +      buffer = { type: '', subtag: '', prefix: [], scope: null }
This seems to be the place where `buffer` first gets initialized. Is it guaranteed that the read file starts with a line starting with `%`?

2022-05-23 13:37 UTC, valentindey commented on tests/all/optionalTests.js
> +                  product_identification_helper: {
Shouldn't this be left out here? I was confused why the test still passed, but looks like test `6.2.1` is giving the one expected warning because the product `CSAFPID-9080701` is not referenced. We might want to check other tests for if they receive the correct warning.

2022-05-23 13:37 UTC, valentindey commented on tests/all/optionalTests.js
> +              product_identification_helper: {
same as above

2022-06-07 11:17 UTC, domachine commented on scripts/bcp-importSubtags.js
> +  const subtags = []
Yes, I feel you. But that was ported from secvisogram and not my decision. I'd suggest that we postpone this a little bit.

2022-06-07 11:18 UTC, domachine commented on scripts/bcp-importSubtags.js
> +      buffer = { type: '', subtag: '', prefix: [], scope: null }
Yes, this is what the file looks like.

2022-06-07 11:43 UTC, valentindey commented on scripts/bcp-importSubtags.js
> +  const subtags = []
Fine for me.

2022-06-07 11:57 UTC, valentindey commented on scripts/bcp-importSubtags.js
> +      buffer = { type: '', subtag: '', prefix: [], scope: null }
If the format is guaranteed, I'm happy :slightly_smiling_face:

2022-06-07 14:18 UTC, domachine commented on tests/all/optionalTests.js
> +                  product_identification_helper: {
Actually, I start to think if it might be better to have more smaller test-cases and run only individual tests against them. This is the danger of one large integrated test-suite 🤔

2022-06-20 23:12 UTC, tschmidtb51 requested changes
Sorry about the long delay in the review. I found a couple issues. Please let me know if something is unclear

2022-06-20 23:12 UTC, tschmidtb51 commented on tests/bcpLanguageTagChecker.js
> +    const privateUseLanguages = ['qtx']
Maybe also add some in the range here?
```suggestion
    const privateUseLanguages = ['qaa', 'qtx', 'qtz']

2022-06-22 08:29 UTC, domachine commented on lib/optionalTests/optionalTest_6_2_19.js
> +])
You mean the class CVSSVector? This is still contained in secvisogram and not yet in the lib. I'll file an issue to find a proper abstraction to centralize this in the lib.

2022-06-22 08:33 UTC, domachine commented on lib/optionalTests/optionalTest_6_2_19.js
> +                })
Seems like the cvss 2.0 lib that I use is buggy 😭

2022-06-24 14:42 UTC, tschmidtb51 commented on lib/optionalTests/optionalTest_6_2_19.js
> +                })
According to my tests, this is now fixed. But I also saw that you implemented the cvss2 calculator?

2022-06-24 17:03 UTC, tschmidtb51 reviewed
Overall, looks good. I had only a few minor comments. Please also replace the modified examples with those from https://github.com/oasis-tcs/csaf/pull/562. Then, the diff/hash also reports that those are the same one.

2022-06-29 18:10 UTC, valentindey commented on scripts/bcp-importSubtags.js
> +  const subtags = []
I'm resolving this conversation as I don't see urgent need for change.

2022-06-29 18:24 UTC, valentindey commented on tests/optionalTest_6_2_19/failing/oasis_csaf_tc-csaf_2_0-2021-6-2-19-01.json
> +}
nitpicky: missing newline at the end of the file

![image](https://user-images.githubusercontent.com/8581199/176508983-69151c57-f2de-424d-bf95-0c3d93f1134b.png)

2022-06-29 18:27 UTC, valentindey approved these changes
Apart from the already opened discussions LGTM

2022-06-30 20:15 UTC, tschmidtb51 commented
> nitpicky: missing newline at the end of the file

If the file is without the newline in the OASIS repo, it should also be here without the newline. Otherwise, the hash-based file comparison (diff) will fail...

2022-07-13 15:23 UTC, tschmidtb51 approved these changes
In general: Approved.

Some minor nits - if you want to update those, I could merge it tonight.
Nit: Just checked the files against the OASIS repo and received:
```
oasis_csaf_tc-csaf_2_0-2021-6-2-14-02.json
28c28
< }
\ No newline at end of file
---
> }
oasis_csaf_tc-csaf_2_0-2021-6-2-14-03.json
28c28
< }
\ No newline at end of file
---
> }
oasis_csaf_tc-csaf_2_0-2021-6-2-14-04.json
27c27
< }
\ No newline at end of file
---
> }
oasis_csaf_tc-csaf_2_0-2021-6-2-14-05.json
27c27
< }
\ No newline at end of file
---
> }
oasis_csaf_tc-csaf_2_0-2021-6-2-14-06.json
27c27
< }
\ No newline at end of file
---
> }
oasis_csaf_tc-csaf_2_0-2021-6-2-14-07.json
27c27
< }
\ No newline at end of file
---
> }
oasis_csaf_tc-csaf_2_0-2021-6-2-14-08.json
27c27
< }
\ No newline at end of file
---
> }
oasis_csaf_tc-csaf_2_0-2021-6-2-14-11.json
27c27
< }
\ No newline at end of file
---
> }
oasis_csaf_tc-csaf_2_0-2021-6-2-14-12.json
28c28
< }
\ No newline at end of file
---
> }
```
Looks like that is currently inconsistent...

2022-07-13 15:23 UTC, tschmidtb51 commented on lib/optionalTests/optionalTest_6_2_19.js
> + * it takes the value from there.
`there` seems ambiguous
```suggestion
 * in the `vector`. If the property doesn't exist there but in the metrics objects,
 * it takes the value from the corresponding metrics object.

2022-07-13 16:03 UTC, domachine commented
> In general: Approved.
> 
> Some minor nits - if you want to update those, I could merge it tonight. Nit: Just checked the files against the OASIS repo and received:
> 
> ```
> oasis_csaf_tc-csaf_2_0-2021-6-2-14-02.json
> 28c28
> < }
> \ No newline at end of file
> ---
> > }
> oasis_csaf_tc-csaf_2_0-2021-6-2-14-03.json
> 28c28
> < }
> \ No newline at end of file
> ---
> > }
> oasis_csaf_tc-csaf_2_0-2021-6-2-14-04.json
> 27c27
> < }
> \ No newline at end of file
> ---
> > }
> oasis_csaf_tc-csaf_2_0-2021-6-2-14-05.json
> 27c27
> < }
> \ No newline at end of file
> ---
> > }
> oasis_csaf_tc-csaf_2_0-2021-6-2-14-06.json
> 27c27
> < }
> \ No newline at end of file
> ---
> > }
> oasis_csaf_tc-csaf_2_0-2021-6-2-14-07.json
> 27c27
> < }
> \ No newline at end of file
> ---
> > }
> oasis_csaf_tc-csaf_2_0-2021-6-2-14-08.json
> 27c27
> < }
> \ No newline at end of file
> ---
> > }
> oasis_csaf_tc-csaf_2_0-2021-6-2-14-11.json
> 27c27
> < }
> \ No newline at end of file
> ---
> > }
> oasis_csaf_tc-csaf_2_0-2021-6-2-14-12.json
> 28c28
> < }
> \ No newline at end of file
> ---
> > }
> ```
> 
> Looks like that is currently inconsistent...

Mhm, interesting. I copied them straight from there 🤔

2022-07-14 07:44 UTC, tschmidtb51 commented
> Mhm, interesting. I copied them straight from there thinking

How did you copy the files (from a git or via the web download; from the current master of oasis)?

2022-07-15 06:38 UTC, domachine commented
> > Mhm, interesting. I copied them straight from there thinking
> 
> How did you copy the files (from a git or via the web download; from the current master of oasis)?

I have a clone of the repository, I pulled there and copied the files using unix's `cp` command.

2022-07-15 09:06 UTC, tschmidtb51 commented
> > > Mhm, interesting. I copied them straight from there thinking
> > 
> > 
> > How did you copy the files (from a git or via the web download; from the current master of oasis)?
> 
> I have a clone of the repository, I pulled there and copied the files using unix's `cp` command.

Hmm - let's just merge that. As discussed, there will be an update in the OASIS GitHub Repo...

2022-07-15 09:07 UTC, tschmidtb51 approved these changes
LGTM.

2022-07-15 09:09 UTC, merged